@php($format = app(\App\Support\Formatter::class))
<x-layouts.app title="Session transcript">
    @push('styles')
        <link rel="stylesheet" href="{{ asset('css/screens/telehealth.css') }}?v={{ filemtime(public_path('css/screens/telehealth.css')) }}">
    @endpush
    <div class="tc">
        <a href="{{ route('app.telehealth.show', ['session' => $session]) }}" class="tj-back"><x-ui.icon name="arrow-left" :size="13" :stroke="2.2" />Back to session</a>
        <header class="tc-head">
            <h1>{{ $transcript->label() }}</h1>
            <span class="tele-pill tele-pill--{{ $transcript->isDraft() ? 'warning' : 'success' }}">{{ $transcript->isDraft() ? 'Draft' : 'Reviewed' }}</span>
        </header>
        @if ($transcript->isDraft())
            <x-ui.alert tone="warning">
                This transcript {{ $transcript->source === \App\Domain\Telehealth\TranscriptSource::Ai ? 'was generated by AI and ' : '' }}has not been reviewed. It may contain mistakes and is not part of the clinical record until a clinician has read it and marked it reviewed.
            </x-ui.alert>
        @else
            <p class="tc-meta">Reviewed {{ $format->dateTime($transcript->reviewed_at) }}.</p>
        @endif
        <pre class="tc-body">{{ $body }}</pre>
        @if ($transcript->isDraft())
            <form method="POST" action="{{ route('app.telehealth.transcripts.review', ['session' => $session, 'transcript' => $transcript]) }}" data-submit-once>
                @csrf
                <button type="submit" class="tj-btn tj-btn--primary">Mark as reviewed</button>
            </form>
        @endif
    </div>
</x-layouts.app>
