<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Resend, Postmark, AWS, and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    // Telehealth video (Daily.co). Read through App\Domain\Telehealth\Daily\DailyConfig, which treats blank values
    // and placeholders as unset (no outbound call) and honours `fake` only locally and in tests.
    // Setup and data-protection notes: docs/integrations/daily.md.
    'daily' => [
        'api_key' => env('DAILY_API_KEY'),
        'webhook_secret' => env('DAILY_WEBHOOK_SECRET'),   // base64, generated by us and registered with Daily
        'geo' => env('DAILY_GEO'),                         // optional media region (eu-west-2, af-south-1, …)
        'api_base' => env('DAILY_API_BASE', 'https://api.daily.co/v1'),
        'connect_timeout' => 3,
        'timeout' => 8,
        'fake' => (bool) env('DAILY_FAKE', false),
    ],

];
