<x-layouts.app title="Account security">
    <x-slot:header>
        @include('account._header', ['active' => 'security'])
    </x-slot:header>

    <div class="settings-stack">
        @if ($mfaRequired)
            <x-ui.alert tone="warning" title="Two-factor authentication is required for your role">
                Super Admin access needs a confirmed second step. Set it up below; the Super Admin console stays closed to you until you have scanned the code and entered a valid one.
            </x-ui.alert>
        @endif

        <x-ui.section title="Password" description="Use a password you do not use anywhere else. A password manager makes that easy.">
            <form method="POST" action="{{ route('user-password.update') }}" data-submit-once>
                @csrf
                @method('PUT')
                <x-ui.card>
                    <div class="form">
                        <x-ui.field label="Current password" name="current_password" :required="true" bag="updatePassword">
                            <x-ui.input type="password" name="current_password" bag="updatePassword" autocomplete="current-password" required />
                        </x-ui.field>

                        <x-ui.field label="New password" name="password" :required="true" help="At least 12 characters, with letters and numbers." bag="updatePassword">
                            <x-ui.input type="password" name="password" bag="updatePassword" autocomplete="new-password" required />
                        </x-ui.field>

                        <x-ui.field label="Confirm new password" name="password_confirmation" :required="true" bag="updatePassword">
                            <x-ui.input type="password" name="password_confirmation" bag="updatePassword" autocomplete="new-password" required />
                        </x-ui.field>
                    </div>
                    <x-slot:footer>
                        <x-ui.button type="submit">Update password</x-ui.button>
                    </x-slot:footer>
                </x-ui.card>
            </form>
        </x-ui.section>

        <x-ui.section title="Two-factor authentication" description="Adds a second step when you sign in: a short code from an authenticator app on your phone. It protects your account even if your password is stolen.">
            @if ($state === 'disabled')
                <x-ui.card>
                    <div class="twofa">
                        <x-ui.badge tone="neutral">Off</x-ui.badge>
                        <p class="twofa__text">Two-factor authentication is not on yet. You will need an authenticator app on your phone to set it up.</p>
                    </div>
                    <x-slot:footer>
                        <form method="POST" action="{{ route('two-factor.enable') }}" data-submit-once>
                            @csrf
                            <x-ui.button type="submit" icon="shield-check">Enable two-factor authentication</x-ui.button>
                        </form>
                    </x-slot:footer>
                </x-ui.card>
            @elseif ($state === 'pending')
                <x-ui.card title="Finish setting up" description="Two-factor authentication is not active until you confirm a code.">
                    <ol class="steps">
                        <li class="steps__item">
                            <p class="steps__title">Scan the QR code with your authenticator app</p>
                            {{-- Trusted: this SVG is generated by Fortify from the user's own secret (BaconQrCode), not from request input. --}}
                            <div class="qr" role="img" aria-label="QR code for your authenticator app">{!! $qrSvg !!}</div>
                        </li>
                        <li class="steps__item">
                            <p class="steps__title">Or enter the setup key by hand</p>
                            <p class="steps__row">
                                <code class="setup-key" id="setup-key">{{ $setupKey }}</code>
                                <button type="button" class="btn btn--secondary btn--sm" data-copy data-copy-target="#setup-key" hidden>
                                    <x-ui.icon name="copy" :size="16" /><span class="btn__label" data-copy-label data-copied-label="Copied">Copy key</span>
                                </button>
                            </p>
                        </li>
                        <li class="steps__item">
                            <p class="steps__title">Enter the 6-digit code the app shows</p>
                            <form method="POST" action="{{ route('two-factor.confirm') }}" class="form" data-submit-once>
                                @csrf
                                <x-ui.field label="Authentication code" name="code" bag="confirmTwoFactorAuthentication">
                                    <x-ui.input name="code" bag="confirmTwoFactorAuthentication" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9 ]*" spellcheck="false" required />
                                </x-ui.field>
                                <div>
                                    <x-ui.button type="submit">Confirm and turn on</x-ui.button>
                                </div>
                            </form>
                        </li>
                    </ol>
                    <x-slot:footer>
                        <x-ui.confirm-form
                            :action="route('two-factor.disable')"
                            method="DELETE"
                            title="Cancel setup?"
                            message="The QR code and setup key will be discarded. You can start again at any time."
                            confirm-label="Cancel setup"
                            cancel-label="Keep going"
                            tone="primary"
                            button-label="Cancel setup"
                            button-variant="ghost"
                        />
                    </x-slot:footer>
                </x-ui.card>
            @else
                <x-ui.card>
                    <div class="twofa">
                        <x-ui.badge tone="success" icon="shield-check">On</x-ui.badge>
                        <p class="twofa__text">
                            You will be asked for a code from your authenticator app each time you sign in.
                            @if ($recoveryCount > 0)
                                You have <strong>{{ $recoveryCount }}</strong> unused recovery {{ $recoveryCount === 1 ? 'code' : 'codes' }}.
                            @endif
                        </p>
                    </div>

                    @if ($recoveryCount > 0 && $recoveryCount <= 2)
                        <x-ui.alert tone="warning" title="You are running low on recovery codes" class="twofa__alert">
                            Generate a new set so you are not locked out if you lose your phone.
                        </x-ui.alert>
                    @endif

                    @if ($recoveryCodes !== [])
                        <div class="recovery" id="recovery-box">
                            <h3 class="recovery__title">Your recovery codes</h3>
                            <p class="recovery__text">Keep these somewhere safe, such as a password manager. Each code works once if you cannot use your authenticator app.</p>
                            <ul class="recovery__codes" id="recovery-codes" role="list">
                                @foreach ($recoveryCodes as $code)
                                    <li>{{ $code }}</li>
                                @endforeach
                            </ul>
                            <div class="cluster">
                                <button type="button" class="btn btn--secondary btn--sm" data-copy data-copy-target="#recovery-codes" hidden>
                                    <x-ui.icon name="copy" :size="16" /><span class="btn__label" data-copy-label data-copied-label="Copied">Copy codes</span>
                                </button>
                                <button type="button" class="btn btn--secondary btn--sm" data-print data-print-target="#recovery-box" hidden>
                                    <x-ui.icon name="printer" :size="16" /><span class="btn__label">Print</span>
                                </button>
                            </div>
                        </div>
                    @endif

                    <x-slot:footer>
                        @if ($recoveryCodes === [] && $recoveryCount > 0)
                            <x-ui.button :href="route('account.security', ['codes' => 'show'])" variant="secondary" icon="eye">Show recovery codes</x-ui.button>
                        @endif
                        <x-ui.confirm-form
                            :action="route('two-factor.regenerate-recovery-codes')"
                            method="POST"
                            title="Generate new recovery codes?"
                            message="Your current recovery codes stop working immediately. The new ones are shown once, so be ready to save them."
                            confirm-label="Generate new codes"
                            tone="primary"
                            button-label="New recovery codes"
                            button-variant="secondary"
                            button-icon="refresh"
                        />
                        <x-ui.confirm-form
                            :action="route('two-factor.disable')"
                            method="DELETE"
                            title="Turn off two-factor authentication?"
                            message="Your account will be protected by your password alone, and roles that require two-factor authentication lose access until you set it up again."
                            confirm-label="Turn off"
                            tone="danger"
                            button-label="Turn off"
                            button-variant="ghost"
                        />
                    </x-slot:footer>
                </x-ui.card>
            @endif
        </x-ui.section>
    </div>
</x-layouts.app>
